//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int DirX = 0;
    public const int DirY = 1;
    public const int Action = 2;
    public const int Menu = 3;
    public const int _count = 4;
}
