//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int Horizontal = 0;
    public const int Vertical = 1;
    public const int Action = 2;
    public const int Menu = 3;
    public const int _count = 4;
}
